#!/bin/bash
# Change the color of DualShock 4 LEDS, and also setup udev rules and perms.
# This is a stark contrast to the xpad-leds script; games like Transistor and
# TowerFall make use of the light bar so it needs to be user writable.

# Usage: ds4-lightbar INDEX|all (R G B)|default|off
#   Change per-controller defaults by editing this file.

[[ "${arcadia_path:-}" || $EUID -eq 0 ]] || { echo "Arcadia not loaded."; exit 1; }

rundir=/var/run/ds4-lightbar
sysdir=/sys/bus/hid/drivers/sony

defaults=(
    "0 0 50"
    "50 0 0"
    "0 50 0"
    "50 50 0"
)

[[ -e /etc/ds4-lightbar.conf ]] && . /etc/ds4-lightbar.conf

case ${1,,} in
install)
    cat > /tmp/50-ds4-lightbar.rules <<EOF
# Only DS4 lightbars have the "global" led.
ACTION=="add", SUBSYSTEM=="leds", DRIVERS=="sony", DEVPATH=="*:global", \
 TAG+="ds4leds", RUN+="$module_file udev"
ACTION=="remove", TAG=="ds4leds", RUN+="$module_file udev"
EOF
    cat > /tmp/ds4-lightbar.conf <<EOF
defaults=(
    "0 0 50"
    "50 0 0"
    "0 50 0"
    "50 50 0"
)
EOF
    sudo mv /tmp/50-ds4-lightbar.rules /etc/udev/rules.d/
    if [[ -e /etc/ds4-lightbar.conf ]]; then rm /tmp/ds4-lightbar.conf
    else sudo mv /tmp/ds4-lightbar.conf /etc/; fi
    sudo udevadm control --reload
    ;;
uninstall)
    sudo rm /etc/udev/rules.d/50-ds4-lightbar.rules
    sudo udevadm control --reload
    ;;
udev)
    if [[ $EUID -gt 0 ]]; then echo "Only udev should run this. Go away!"
    else
    exec > /tmp/test 2>&1
    dev=$(basename "$DEVPATH" | sed 's/:global//')
    case "$ACTION" in
    add)
        # Make leds user writeable.
        chmod a+w "$sysdir/$dev/leds/"*"/brightness";
        # We're going to use a run directory from now on so that we don't have
        # to sort by creation time every time we run the script, and so that
        # it can imitate the behavior of MoltenGampead where slots aren't
        # flattened down.
        mkdir -p "$rundir"
        # Find a free index.
        for ((index = 0; ; index++)); do
            if ! [[ -d "$rundir/$index" ]]; then
                ln -s "$sysdir/$dev/leds" "$rundir/$index"
                "$0" $((index + 1)) default
                break
            fi
        done ;;
    remove)
        for dir in "$rundir/"*; do
            [[ ! -e "$dir" || -e "$dir/$dev:global" ]] && rm "$dir"
        done ;;
    esac
    fi ;;
*)
    if [[ "$#" =~ 0|1|3 ]]; then
        echo "Usage: arcadia ds4-lightbar INDEX|all (R G B)|default|off"
        echo "  Edit /etc/ds4-lightbar.conf to set the default colors."
        exit 1
    else  # Convenient light-changing API.
        index=${1:?};  # Index refers to the nth available controller.
        r=${2:-}; g=${3:-}; b=${4:-}
        
        # Define a function rather than repeating ourselves ad nauseum.
        set_led () {
            local index=$((${1:?} - 1))
            led="$rundir/$index"; [[ -e "$led" ]] || return
            if [[ "${2:?}" == "off" ]]; then
                echo 0 > "$led/"*"global/brightness"
            elif [[ "${2:?}" == "default" ]]; then
                set_led "${1:?}" ${defaults[index % ${#defaults[@]}]}
            else
                echo 1 > "$led/"*"global/brightness"
                echo "${2:?}" > "$led/"*"red/brightness"
                echo "${3:?}" > "$led/"*"green/brightness"
                echo "${4:?}" > "$led/"*"blue/brightness"
            fi
        }
        
        if [[ "$index" == "all" ]]; then
            for i in $(seq 1 $(ls -1 $rundir | wc -l)); do
                set_led "$i" "$r" "$g" "$b";
            done;
        else set_led "$index" "$r" "$g" "$b"; fi
    fi
    ;;
esac
