#!/bin/bash
# Turns the discrete GPU on and off on demand. Safer to put this in sudoers.d
# than its component commands.

fullpath=$(readlink -f "$0")
[[ $EUID -gt 0 ]] && exec sudo "$fullpath" "$@"

nvidia_ver=$(find /usr/lib | sed -nr 's:^.*nvidia-([0-9]+).*$:\1:p' | tail -1)

case ${1,,} in
on)
    echo ON > /proc/acpi/bbswitch
    modprobe nvidia || modprobe "nvidia_${nvidia_ver}"
    ;;
off)
    rmmod nvidia_drm || rmmod "nvidia_drm_${nvidia_ver}" || true
    rmmod nvidia_modeset || rmmod "nvidia_modeset_${nvidia_ver}" || true
    rmmod nvidia_uvm || rmmod "nvidia_uvm_${nvidia_ver}" || true
    rmmod nvidia || rmmod "nvidia_${nvidia_ver}" || true
    echo OFF > /proc/acpi/bbswitch
    ;;
query)
    cat /proc/acpi/bbswitch ;;
install)
    cat > /etc/sudoers.d/arcadia-nvidia <<EOF
ALL ALL=(ALL) NOPASSWD: $fullpath
EOF
    ;;
esac
