#!/bin/bash
# Receives the full path to a game to run, and runs it.
[[ "$arcadia_loaded" ]] || { echo "Arcadia not loaded."; exit 1; }

game="$(readlink -f "$1")"
check_platform! "$(dirname "$game")"
load_platform "$(dirname "$game")"
load_game "$game" || die "Failed to load $game."
include /tmp/arcadia-session.meta  # Temporary file that launchers can make.
set_runner $platform
[[ "$steam_id" ]] || find_file
arcadia run run_game
[[ -f /tmp/arcadia-session.meta ]] && rm /tmp/arcadia-session.meta
