#!/bin/bash
# Receives the full path to a game to run, and runs it, optionally with args.
[[ "${arcadia_loaded:-}" ]] || { echo "Arcadia not loaded."; exit 1; }

# Used for multi-file games. This function should do nothing except for in
# the context of actually running a game.
select_file () { _select_file "$@"; }

game=""
find_game "${1:?}"; shift
check_platform! "$(dirname "$game")"
load_platform "$(dirname "$game")"
load_game "$game" || die "Failed to load $game."
include /tmp/.arcadia-session.meta || true
include /tmp/arcadia-session.meta || true
set_runner "${platform:-}"
[[ "${steam_id:-}" ]] || find_file
run run_game "$@"
[[ -f /tmp/arcadia-session.meta ]] && rm /tmp/arcadia-session.meta
