#!/bin/bash
# Wrapper for all of Arcadia's modules.

set -eu -o pipefail +o monitor
if [[ "${ARCADIA_TRACE:-}" ]]; then set -o xtrace; fi

# Find Arcadia.
arcadia_bin=$(readlink -f "${0:-}"); export arcadia_bin
this_dir=$(dirname "$arcadia_bin")
for arcadia_dir in "${ARCADIA_PATH:-}" "$this_dir" \
 "$(readlink -f "$this_dir/../share/arcadia")" \
 "${XDG_DATA_HOME:-$HOME/.local/share}/arcadia"; do
 if [[ -f "$arcadia_dir/runners/pc" ]]; then
    export arcadia_path="$arcadia_dir"
    break
fi; done; unset arcadia_dir
[[ ! -d "$arcadia_path" ]] && { echo "FATAL: Couldn't find Arcadia!"; exit 1; }

# Load up all of Arcadia's stuff.
for funcs in "$arcadia_path/funcs/"*;   do . "$funcs"; done
for funcs in "$arcadia_path/runners/"*; do . "$funcs"; done; unset funcs

load_config
load_controllers
if [[ "${arcadia_game:-}" ]]; then
    load_game "${arcadia_game:-}"
    include "/run/user/$UID/arcadia/session.meta" || true
fi
mkdir -p "/run/user/$UID/arcadia" || true  # Argument list too long?????

module "$@"
