#!/bin/bash

# shellcheck disable=SC2034
declare -A aliases=([pcsx]="pcsxr" [pcsx2]="PCSX2" [dolphin_emu]="dolphin-emu")

runner_psx () {
    bin psx "${dir:?}/${file:?}"
}

runner_pcsx () {
    bin pcsx -nogui -cdfile "${dir:?}/${file:?}"
}

runner_epsxe () {
    bin epsxe -nogui -loadiso "${dir:?}/${file:?}"
}

runner_mupen64plus () {
    bin mupen64plus "${dir:?}/${file:?}"
}

runner_pcsx2 () {
    # Default settings.
    local aspect=${aspect:-4:3}; local wspatches=${wspatches:-disabled}
    if is "${widescreen:-}"; then { aspect=16:9; wspatches=enabled; }; fi
    
    # Substitutions.
    local inidir="${pcsx2_inidir:-$HOME/.config/PCSX2/inis_1.4.0}"
    sed -r -i -e 's/(EnableWideScreenPatches\s*=\s*).+/\1'"$wspatches"'/i' \
     "$inidir/PCSX2_vm.ini"
    sed -r -i -e 's/(AspectRatio\s*=\s*).+/\1'"$aspect"'/i' \
     "$inidir/PCSX2_ui.ini"
    
    # Start the game.
    if [[ "${gamefixes:-}" ]]; then
        bin pcsx2 "--gamefixes=${gamefixes:-}" --nogui "${dir:?}/${file:?}"
    else bin pcsx2 --nogui "${dir:?}/${file:?}"; fi
}

runner_dolphin_emu () {
    bin dolphin_emu -b -e "${dir:?}/${file:?}"
}
