#!/bin/bash
# Bases for all multi-platform runners.

runner_mednafen () {
    local sound_device="default"
    pgrep pulseaudio && sound_device="pulse"
    platform="${platform:?}"; local module="$platform"
    [[ "$platform" = "gen" ]] && module="md"
    local med_saves="${saves_dir:?}/$platform/mednafen"; mkdir -p "$med_saves"
    bin! mednafen -path_sav "$med_saves" -path_state "$med_saves" \
     -sound.device "$sound_device" -force_module "$module" \
     "${dir:?}/${file:?}"
}


# RetroArch is a runner that has its own subset of runners. Bluh.
declare -A libretro_cores=(
    [arc]="mame fbalpha fba"  # It's probably better to set this per-game.
    [nes]="fceumm nestopia quicknes"
    [gen]="picodrive genesis_plus_gx"
    [snes]="bsnes_mercury_accuracy bsnes_mercury_balanced"
    [sat]="yabause"
    [psx]="mednafen_psx beetle_psx"
    [n64]="glupen64 mupen64plus"
    [sdc]="reicast"
    [gb]="mednafen_vb beetle_vb gambatte"
    [gg]="genesis_plus_gx"
    [gba]="mednafen_gba beetle_gba mgba vbam vba_next gpsp"
    [nds]="desmume"
    [psp]="ppsspp"
)
libretro_cores[snes]+="bsnes_mercury_performance bsnes_accuracy bsnes_balanced"
libretro_cores[snes]+="bsnes_performance snes9x snes9x_next"

runner_retroarch () {
    libretro_find_core
    local configs=(); local args=();
    for c in "${platform_dir:?}/retroarch.cfg" "${dir:?}/retroarch.cfg"; do
        [[ -e "$c" ]] && configs+="$c;"; done
    if [[ "${configs[0]}" ]]; then
        echo 'config_save_on_exit = "false"' > /tmp/.ra-append.cfg
        args+=(--appendconfig "${configs//;/|}/tmp/.ra-append.cfg")
    fi
    bin retroarch "${args[@]}" -L "${libretro_core:?}" \
     -s "${saves_dir:?}/${platform:?}" -S "${saves_dir:?}/${platform:?}" \
     "$dir/$file"
    rm /tmp/.ra-append.cfg
}

libretro_find_core () {
    for libretro_dir in "${libretro_cores_dir:-}" \
     $(find /usr/lib -type d -name libretro); do
        for core in ${libretro_cores[$platform]]}; do
            libretro_core="$libretro_dir/${core}_libretro.so"
            [[ -e "$libretro_core" ]] && { break 2; }
        done
    done
    [[ -e "$libretro_core" ]] || return 1
}
