#!/bin/bash
# Functions for the desktop generator.

# Generate a directory file from data/platform-template.directory, using
# the name of the platform folder. That is, if the user refers to the
# Gensis as Megadrive instead, it will appear as such in the menu.
gen_directory () {
    sed -e "s|%name%|$plat_base|g" -e "s|%platform%|$platform|g" \
     -e "s|%icon%|$arcadia_path/icons/$platform.png|g" \
     "$arcadia_path/data/platform-template.directory" > "$1"
}

# Generate a desktop file drom data/game-template.desktop.
gen_desktop () {
    local gen_out=""; local gen_cat=""; local g
    for g in "${genres[@]}"; do gen_out+="$g;"; gen_cat+="X-Arcadia-$g;"; done
    find_image icon || icon="arcadia-$platform"
    find_image boxart
    find_image screenshot
    sed -e "s|%name%|$name|g" -e "s|%game%|$game|g" -e "s|%icon%|$icon|g" \
     -e "s|%boxart%|$boxart|g" -e "s|%screenshot%|$screenshot|g" \
     -e "s|%platform%|$platform|g" -e "s|%genres%|$gen_out|g" \
     -e "s|%arcgenres%|$gen_cat|g" -e "s|%arcbin%|$arcadia_bin|g" \
     "$arcadia_path/data/game-template.desktop" > "$1"
}

# Cleans up game variables between each generation to prevent mixing up info.
clear_game () {
    unset name genres dgpu padfile icon boxart screenshot
}
