#!/bin/bash

start_wm () {
    debug_print "Starting window manager"
    # User knows best.
    if [[ "$xinit_wm" ]]; then $xinit_wm &
    # Else detect based on what is available. We don't use the bin function
    # because it's overkill and also it can't run a program without args;
    # only determine if it exists when args are not passed.
    elif shh which fluxbox;  then fluxbox -no-slit -no-toolbar &
    elif shh which xfwm4;    then xfwm4 --compositor off &
    elif shh which metacity; then metacity --no-composite &
    elif shh which openbox;  then openbox &
    # No window manager.
    else die "No suitable window manager found. Please install fluxbox."; fi
}

# Set a nice background. Useful to make sure the server is actually running,
# and when combined with an aspect-correct fullscreen window, makes pillarboxes
# look a lot nicer.
set_background () {
    bin feh || return 0
    if is $xinit_bg_xfconf && bin xfconf-query; then
        feh --bg-fill "$(xfconf-query -c xfce4-desktop -p \
         /backdrop/screen0/monitor0/workspace0/last-image)"
    elif [[ -e "$conf_dir/xinit_bg" ]]; then
        feh --bg-fill "$conf_dir/xinit_bg"
    elif [[ -e "$conf_dir/xinit_bg.png" ]]; then
        feh --bg-fill "$conf_dir/xinit_bg.png"
    elif [[ -e "$conf_dir/xinit_bg.jpg" ]]; then
        feh --bg-fill "$conf_dir/xinit_bg.jpg"
    fi
}

# Some apps behave really badly without a tray around.
# By default the tray will stick around but you can hide it through config.
start_tray () {
    debug_print "Starting stalonetray"
    shh stalonetray -t --window-layer bottom &
    if is $hide_tray; then
        (sleep 1 && xdotool search --class stalonetray windowunmap) &
    fi
}

# Allows use of the intel outputs when running on the dgpu.
prime_xrandr () {
    is $dgpu && is $primex || return
    #prime-offload
    xrandr --setprovideroutputsource modesetting NVIDIA-0
    xrandr --auto
}
